ricos/config/routes.rb
Ricos::Application.routes.draw do
  resources :availables

  match "/auth/:provider/callback" => "availables#index"
  match "/sign_out" => "sessions#destroy", :as => :sign_out
  root :to => 'home#index'

end

ricos/app/models/available.rb
class Available < ActiveRecord::Base
  attr_accessible :begin_at, :name
end

ricos/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :provider, :uid
end

ricos/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

ricos/app/controllers/availables_controller.rb
class AvailablesController < ApplicationController
  # GET /availables
  # GET /availables.json
  def index
    @availables = Available.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @availables }
    end
  end

  # GET /availables/1
  # GET /availables/1.json
  def show
    @available = Available.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @available }
    end
  end

  # GET /availables/new
  # GET /availables/new.json
  def new
    @available = Available.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @available }
    end
  end

  # GET /availables/1/edit
  def edit
    @available = Available.find(params[:id]) 


  end

  # POST /availables
  # POST /availables.json
  def create
    @available = Available.new(params[:available])

    respond_to do |format|
      if @available.save
        format.html { redirect_to @available, notice: 'Available was successfully created.' }
        format.json { render json: @available, status: :created, location: @available }
      else
        format.html { render action: "new" }
        format.json { render json: @available.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /availables/1
  # PUT /availables/1.json
  def update
    @available = Available.find(params[:id])
    @available.available = "1"
    @available.save
    # Pusher.trigger!("miapp", "available:create", {})
    redirect_to availables_path
  end

  # DELETE /availables/1
  # DELETE /availables/1.json
  def destroy
    @available = Available.find(params[:id])
    @available.destroy

    respond_to do |format|
      format.html { redirect_to availables_url }
      format.json { head :no_content }
    end
  end
end

ricos/app/controllers/home_controller.rb
class HomeController < ApplicationController
end

ricos/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
  	
  end

  def destroy
  end
end

ricos/app/helpers/application_helper.rb
module ApplicationHelper
end

ricos/app/helpers/availables_helper.rb
module AvailablesHelper
end

ricos/app/helpers/sessions_helper.rb
module SessionsHelper
end

ricos/app/views/availables/_form.html.erb
<%= form_for(@available) do |f| %>
  <% if @available.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@available.errors.count, "error") %> prohibited this available from being saved:</h2>

      <ul>
      <% @available.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :begin_at %><br />
    <%= f.text_field :begin_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ricos/app/views/availables/edit.html.erb
<h1>Editing available</h1>

<%= render 'form' %>

<%= link_to 'Show', @available %> |
<%= link_to 'Back', availables_path %>

ricos/app/views/availables/index.html.erb
<h1>Mesas Disponibles</h1>

<table>
  <tr>
    <th>Mesa 01 <br />27/11/2012</th>
  </tr>

<% @availables.each do |available| %>
  <tr>
    <td>
      <%= form_for available do |f| %>
       <% if available.available == "1" %>
       <%= f.submit available.begin_at.strftime("%H:%M:%S"), :class => "btn btn-danger" %>
       <% else %>
       <%= f.submit available.begin_at.strftime("%H:%M:%S"), :class => "btn btn-success" %>
       <% end %>
      <% end %>
     <br>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Available', new_available_path %>

ricos/app/views/availables/new.html.erb
<h1>New available</h1>

<%= render 'form' %>

<%= link_to 'Back', availables_path %>

ricos/app/views/availables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @available.name %>
</p>

<p>
  <b>Begin at:</b>
  <%= @available.begin_at %>
</p>


<%= link_to 'Edit', edit_available_path(@available) %> |
<%= link_to 'Back', availables_path %>

ricos/app/views/home/index.html.erb
<h2>Pagina de bienvenida</h2>
<%= link_to "Inicia Sesion con Twitter", "/auth/twitter" %> <br />
<%= link_to "Inicia Sesion con Facebook", "/auth/facebook" %>

ricos/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ricos</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>